#!/usr/bin/env php
<?php

use DatabaseImporter\Argv;
use DatabaseImporter\CommandHandler;
use DatabaseImporter\model\Database;
use DatabaseImporter\model\DatabaseImporterCommandConfigInterface;


set_time_limit(0);

require dirname(__DIR__) . '/vendor/autoload.php';

class ExampleDatabaseImporterCommandConfig implements DatabaseImporterCommandConfigInterface
{
    public function getCommandName(): ?string
    {
        return null;
    }

    public function getSource(): Database
    {
        return new Database(
            "source_database_test",
            "127.0.0.1",
            "username",
            "password"
        );
    }

    public function getDestination(): Database
    {
        return new Database(
            "destination_database_test",
            "127.0.0.1",
            "username",
            "password"
        );
    }
}

$commandHandler = new CommandHandler();
try {
    $commandHandler
        ->set(new ExampleDatabaseImporterCommandConfig())
        ->run(new Argv());

} catch (Exception $e) {
    die($e->getMessage());
}